security:
  oauth2:
    client:
      clientId: <insert your client id> 
      clientSecret: <insert your client secret>
      accessTokenUri: https://<insert your open id hostname>/oidc/token
      userAuthorizationUri: https://<insert your open id hostname>/oidc/authorize
      tokenName: oauth_token
      scope: bona_fide_status, openid 
    resource:
      userInfoUri: https://<insert your open id hostname>/oauth/rpc/json/oidcManager/userinfo
#sample #1
querySamples:
  assembly-id-1: GRCh37
  position-1: 6689
  reference-name-1: 17
  alternate-bases-1: 
  dataset-ids-1: 
#sample #2
  assembly-id-2: GRCh37
  position-2: 1040026
  reference-name-2: 1
  alternate-bases-2: 
  dataset-ids-2: EGAD00001000740,EGAD00001000741
#sample #3
  assembly-id-3: GRCh37
  position-3: 1040026
  reference-name-3: 1
  alternate-bases-3: C
  dataset-ids-3: EGAD00001000740
