version: '3.2'

# Use the default driver (here bridge)
networks:
  beacon-priv:
  beacon-pub:

# Use the default driver for volume creation
volumes:
  beacon-db:

services:

  db:
    environment:
      - POSTGRES_USER=microaccounts_dev
      - POSTGRES_PASSWORD=r783qjkldDsiu
      - POSTGRES_DB=elixir_beacon_dev
      - PGDATA=/beacon-db
    hostname: beacon-db
    container_name: beacon-db
    build: db
    image: egarchive/beacon-db:latest
    volumes:
      - beacon-db:/beacon-db
    ports:
      - "5432:5432"
    networks:
      - beacon-priv

  beacon:
    depends_on:
      - db
    image: egarchive/beacon:elixir-1.0.1
    hostname: beacon
    container_name: beacon
    volumes:
      - ./dev-1.1.0.properties:/beacon/application.properties
    ports:
      - "9075:9075"
    networks:
      - beacon-priv
      - beacon-pub
